install.packages('readxl')
install.packages('readr')
library('readr')
library('readxl')
inv<-read.csv("Inventory Report_July 21, 2022.csv",header=TRUE)
head(inv)
as.factor(inv$Category)
parse_number(inv$Category)
log(inv$Category)
